### ISSUE TITLE
workflow fails on Run actions/setup-node@v1

### ISSUE THREAD

**Issue by BrightRan** [actions/setup-node#199]
Associated GitHub Community ticket: https://github.community/t/ci-started-to-fail-on-run-actions-setup-node-v1/131883

The customer is using CI workflow to generate NPM package. Recently, the workflow started to fail when running actions/setup-node@v1 .
The customer said that they did not changed any configurations of workflow.
The following is the error message:
```js
Run actions/setup-node@v1
  with:
    node-version: 12
    registry-url: https://npm.pkg.github.com/
    scope: @ierp-ai
    always-auth: false
##[error]No such file or directory
##[debug]System.ComponentModel.Win32Exception (2): No such file or directory
##[debug]   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
##[debug]   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
##[debug]   at System.Diagnostics.Process.Start()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Run actions/setup-node@v1
```

**Comment by khhhum** [comment]
Adding some details to this

* We started hitting this issue some time at night thursday september 10th
* We are using self-hosted runners, on ubuntu 18.04 
* We see the problem for multiple marketplace as well as custom actions, e.g. also "setup-java"
* Forcing the runnings back onto the previous version 2.273.0 seems to make it work again, but since they are auto-upgraded it is not a useful workaround
* It seems like there is a race condition involved as it will work sometimes, but not very often. Stomach feeling is it fails >90% of the time
* it becomes a bigger problem because you cannot re-run a single job, only all of them

Let me know what other details you need
